[package]
name = "please"
version = "2.0.0"
edition = "2024"
authors = ["Raiyan Bin Rashid <raiyanbinrashid0@gmail.com>"]
description = "An AI-native git CLI. You never type raw git commands."
license = "Apache-2.0"
repository = "https://github.com/HylithLabs/please"
homepage = "https://github.com/HylithLabs/please"
readme = "README.md"

[package.metadata.wix]
upgrade-guid = "7077AC17-B90D-4753-9524-23B45C53C304"
path-guid = "3D3F9CF7-BE4C-45E3-A21F-F442B48602E1"
license = false
eula = false

[dependencies]
axoupdater = { version = "0.10.0", features = ["blocking"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ureq = { version = "3.3.0", features = ["json"] }
termimad = "0.31"
owo-colors = "4.1.0"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
