use axoupdater::AxoUpdater;

use crate::ui;

/// Self-updates the `please` binary in place, using the install receipt
/// left behind by the shell/PowerShell installer or Homebrew tap (both
/// generated by cargo-dist). Only works for binaries installed that way —
/// a `cargo install`-built binary has no receipt to update from, so it's
/// told to rebuild from source instead of failing mysteriously.
pub fn run(args: &[String]) {
    if args.first().map(|s| s.as_str()) == Some("ignore") {
        crate::update_checker::ignore_latest_version();
        return;
    }

    ui::step("Checking for updates");

    let mut updater = AxoUpdater::new_for("please");
    let updater = match updater.load_receipt() {
        Ok(updater) => updater,
        Err(err) => {
            ui::warn(&format!("Can't check for updates: {err}"));
            ui::detail("installed via cargo install? run it again to rebuild from source.");
            ui::detail("installed via Homebrew? run `brew upgrade please` instead.");
            std::process::exit(1);
        }
    };

    match updater.run_sync() {
        Ok(Some(result)) => {
            ui::success(&format!("updated to v{}", result.new_version));

            // Fetched by "latest", not by reconstructing a `v{version}` tag:
            // release tags haven't been consistent (some are `v0.1.5`, the
            // 0.1.6 release is tagged plain `0.1.6`), so guessing the tag
            // 404s silently and this never prints. `please update` always
            // lands on the newest release anyway, so asking GitHub for
            // "latest" sidesteps the tag format entirely.
            if let Ok(mut response) =
                ureq::get("https://api.github.com/repos/HylithLabs/please/releases/latest")
                    .header("User-Agent", "please-cli")
                    .call()
                && let Ok(body_str) = response.body_mut().read_to_string()
                && let Ok(json) = serde_json::from_str::<serde_json::Value>(&body_str)
                && let Some(body) = json.get("body").and_then(|s| s.as_str())
            {
                println!("\n🚀 What's New:\n");
                ui::print_markdown(body);
            }
        }
        Ok(None) => ui::success("already up to date"),
        Err(err) => {
            ui::error(&format!("update failed: {err}"));
            std::process::exit(1);
        }
    }
}
